name: "General Development Task"
description: Track standard development work that isn't a bug or feature request
title: "[DEV] "
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Development Task
        Use this template for standard development work that isn't a bug fix or new feature.

  - type: dropdown
    id: task-type
    attributes:
      label: Task Type
      description: What type of development task is this?
      options:
        - New Feature
        - Implementation
        - Refactoring
        - Performance Optimization
        - Testing
        - Integration
        - Configuration
        - Dependency Update
        - Research/Spike
        - DevOps
        - Other (specify in description)
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what needs to be done
      placeholder: Implement the user authentication flow using OAuth...
    validations:
      required: false

  - type: textarea
    id: user-stories
    attributes:
      label: User Stories
      description: Please provide user stories that would be fulfilled by this feature
      placeholder: |
        As a [type of user], I want [some goal] so that [some reason].
        
        Examples:
        - As a customer, I want to save my payment methods so that I don't have to re-enter them for each purchase.
        - As an admin, I want to see failed login attempts so that I can monitor for suspicious activity.
    validations:
      required: false

  - type: textarea
    id: ui-notes
    attributes:
      label: User Interface Notes
      description: Please provide information, descriptions, notes, and other documentation on the user interface and its desired look or behavior.
      placeholder: |
        Wireframe Link/s:
        Field Specifications:
    validations:
      required: false

  - type: textarea
    id: actions-events
    attributes:
      label: Actions and Events
      description: Please provide information, descriptions, notes, and other documentation on actions that the user can do and the events associated with those actions.
      placeholder: |
        Action A
        - When the user clicks... then the system should...
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What conditions must be met for this feature to be considered complete?
      placeholder: |
        - The system must allow users to...
        - The feature should handle the case when...
        - Performance should not degrade by more than...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Perceived Priority
      description: How important do you think this feature is?
      options:
        - Critical (needed for core functionality)
        - High (significant improvement to existing functionality)
        - Medium (useful enhancement)
        - Low (nice to have)
    validations:
      required: false

  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      description: If you have technical knowledge, how complex do you think this would be to implement?
      options:
        - Unknown
        - Small (hours)
        - Medium (days)
        - Large (weeks)
        - Extra Large (months)

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here.
      placeholder: Add any other relevant details here.
